# Generated by Django 2.1 on 2019-01-01 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190101_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 1, 11, 24, 30, 79064, tzinfo=utc)),
        ),
    ]
