# Generated by Django 2.1 on 2019-01-02 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20190101_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentor',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=mysite.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 2, 6, 44, 26, 22541, tzinfo=utc)),
        ),
    ]
