# Generated by Django 2.1 on 2019-01-02 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20190102_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 2, 7, 35, 19, 817553, tzinfo=utc)),
        ),
    ]
