# Generated by Django 2.1 on 2019-01-02 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20190102_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 2, 7, 49, 48, 873187, tzinfo=utc)),
        ),
    ]
