# Generated by Django 2.1 on 2019-01-02 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20190102_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_count',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 2, 7, 58, 51, 567082, tzinfo=utc)),
        ),
    ]
